#+title: 自营销(Baked In: Creating Products and Businesses That Market Themselves)

#产品有故事#一杯咖啡不止是一杯咖啡，一副太阳镜不止是一副太阳镜，一辆汽车不止是一辆汽车。产品里蕴藏着它代表的故事，这才是我们真正销售的东西——品牌的内涵。

在当今世界中，花费与设计广告活动等量的时间，人们已经可以把消费者对产品的见解融入到新的产品里面去。设计一种怀着使命的产品，一种有故事可讲的产品，一种能够自己推销自己的产品。

营销在讲述一个有关公司的故事，它大多与高层的企业战略相关；而产品却根据产品经理自身的愿景，讲述着若干其他的故事。再加上，负责产品生产的人并不理解产品形式中所体现的公司品牌的意义（或是理解了也得不到奖励），问题就变得更加复杂了。

对许多公司来说，是时候该打破内部的壁垒了。它们必须意识到，合作是“营销-创新模式”的核心。跟客户合作固然是关键，而组织内部的合作更为关键。企业及其品牌是依靠了不起的创新产品建立起来的。品牌和营销必须重新与产品本身连接到一起。设计新流程的目的，应当是在同一个强有力故事的推动下，把市场营销和产品设计提升到战略层面。因此，卓越的设计师和营销人员必须携手合作，共同创造形式与故事相一致的产品。

进化要求我们不断更新自己的竞争优势。永远创新不是远大志向，而是根本的设计规范。它不是战略，而是必需。

传统广告缺席所带来的沟通真空，可以让消费者们来填满。在消费者碰到自己喜欢的产品和公司时，他们其实是迫切想要帮忙代言讲故事的。

同样，靠大众营销方式建立的企业，往往容易开发出雷同的产品。它们打磨掉产品的棱角，取消了特色的功能，想让产品适用于普罗大众。它们利用小组讨论，确保产品“可以被用户接受。”这样的产品当然不会得罪任何人，但“可以被用户接受”永远是最冒险的策略。因为在当今的市场环境中，“可以被用户接受”的产品有着高得惊人的失败率。更可怕的是，我们似乎并未意识到这些失败，因为从一开始，我们就没有注意过这些失败的产品。所以，等它们消失的时候，就好像什么也没有发生过一样，没有哈佛商学院的案例记载，没有登上报纸头条，也没有新闻报导。它就像《洋葱》（The Onion）讽刺新闻杂志上的一条标题：“产品停产没有引起任何人的注意，记者甚至都懒得提问。”

#命名力#你永远、永远、永远也不要低估名字里蕴涵的营销能量。想想看，要是产品有个跟文化联系在一起的名字，那么它将获得多大的推动力？

#故事力#一个动人心魄的故事会永远地进驻消费者的内心。对于企业而言，最合适的故事，莫过于让产品设计和市场营销从一开始就结合在一起，让所有参与者都为同一个故事添砖加瓦，是实现浑然天成的唯一途径。

确保所有参与者都为同一个故事添砖加瓦，是实现浑然天成的唯一途径。

使用产品本身来讲这类故事的想法是与传统市场营销相悖的，特别是对一家大公司来说，这是一个很陌生的领域。尽管很多创业型企业能靠直觉来做到这一点，可就跟我们说的一样，大部分大公司真的很难弄明白其中的道理。

故事能够很好地把人们连接起来，因为故事早就被融入了我们的DNA。人类之所以为人类，就是因为我们不但会讲故事，还具备分享故事的能力。故事为我们所做的一切带来了背景和意义；故事承载着我们的希望、梦想和价值观；故事唤起我们的好奇心，给我们带来惊喜和神奇；故事在我们灵魂深处引起共鸣。而且，如果故事讲得好，就能永远地进驻我们的心。

最合适的故事，是把产品设计和市场营销从一开头就结合在了一起，而不是通过后期零零散散地加入。

要取得成功，品牌故事必须跟文化当中更宏观的对话联系起来。不这么做的话，故事就缺乏时代性。把市场营销建立在缺乏时代性的故事上，就没人会注意到它，产品也卖不出去。

人们渴望与生产自己所买产品的企业建立起人性的关系。良好品牌的基石，在于讲述精彩的故事——但这是一条双向车道。企业必须靠着倾听、理解消费者的故事，不断改进自己的故事。从这里出发，他们可以创造出更深刻、联系更加紧密的故事，文化进而可以得到不断优化。

#极端力#如果最快管用，最慢也行；如果最重管用，最轻也行；如果最吵闹管用，最安静也行。最不管用的就是两头不靠在中间：有点安静，有点快，有点轻。如果说，你没法想出一种走极端的方式，那这个点子还是算了吧。

#无形力#让无形的东西变得让人看得见，是把营销融入产品的一种有力方式。要把了不起的想法植入产品中，而不是包装上。包装可以扔掉，而产品不会。

#冲突力#冲突，造就了产品的唯一性，这正是让产品脱颖而出的关键。最成功的品牌把文化的冲突和张力作为杠杆，推动变革，最终改变了文化。

害怕还是一种好用的记号。每当你投入到全新的世界里，它就会提醒你。人人都对未知的东西有点小小的恐惧。在这种背景下经历害怕，你就知道，要是你脖子后面的汗毛立了起来，呼吸紧张了起来，那就是来到真正的创新空间了。回应这些感觉，大胆参与游戏吧。

脱落，要多多尝试。害怕脱落，是攀岩最大的障碍，它可以解释成几件事。如果你中途不脱落就能到顶，那就主动从确保安全的锚点往下跳好了。要是你总想着脱落，那就永远不会努力挑战自己的难度极限。你的注意力无法集中在下一步动作上，而是想着脱落。之后，你大概就放弃了。 尝试，尝试，不断尝试。千万别说“收紧绳子！”不停尝试，直至脱落。而且，就算你认为自己精疲力竭了，马上就要脱落了，也要使劲试试看。你一定会惊讶于自己最终居然能完成目标，爬到最高处。真的，我向你保证。 而且，竭尽全力地拼搏，往往会叫你感到更加快乐。它将成为你难忘的记忆。在攀爬线路之前说服自己是最困难的，因为那时候，你觉得脱落是必然的。所以，你干脆别去想它，多想想我说的这种情况。说“收紧绳子放我下来”或者“我自己爬下来”，这倒是容易很多，但其实你很可能低估了自己的能力。要用如同核弹头般的威力来武装自己，攀爬一条超出你自认能力范围之外的线路，与其说是在训练，不如说是在大胆尝试。 脱落并不是失败，脱落是成功的一环。

#破坏性营销#你必须打破规则，把产品设计得一眼看上去就与众不同。如果你做到了，不光产品脱颖而出，竞争对手的争相效仿也会成为你的最佳广告。

#商业直觉#最真实的创新却来自偶然的随意之举。有效的设计直觉根植于现实、逻辑、知识和经验。从“擅长”产品和营销创新到“精通”产品和营销创新，设计直觉是必经之路。

是时候该认识到这一点了：比起发明创造，我们人类更擅长理解，更擅长修修补补。但我们并不知道，我们真的生活在秩序的幻觉里，我们总相信事情能够规划和预测。我们害怕随机，但我们却生活在它结出的果实里。我们太害怕随机了，怕到创建出了试图理解过去的学科——但最终，我们是要失败的，就好像我们没办法看清未来一样。

靠直觉建立的品牌，很可能更具破坏性，更能适应并利用瞬息万变、不可预测的环境。反过来说，由于无法创新、不能凭借自身的力量更新，许多老品牌越做越艰难。这就意味着，有时候，为了让别的东西能够茁壮成长起来，不相关的产品、品牌，甚至整个商业结构都得垮台。直觉能为这一灵感、竞争和文化重建过程提供燃料。

通常情况下，人们把直觉看成你对某种东西的本能感觉。普通的直觉或许能在你的日常生活里发生作用，设计直觉却略有不同，它是出色创新决策背后的驱动力。你可以这样看待设计直觉：它是一种工具，在你面对以前没碰到过的新问题时，它能让你把理性思考和情绪感觉嫁接起来，将经验转化成行动。有效的设计直觉应当根植于现实、逻辑、知识和经验。

正如我们所见，从擅长产品和营销创新到精通产品和营销创新，设计直觉是必经之路。但要闯入未知的未来，还要把勇气摆在设计直觉的核心。 设计规划流程把产品变得越来越雷同，这种事情实在太多了。渐进式改良不是真正的创新。卓越的品牌从文化上就以直觉为基础，是直觉，令品牌有了超越竞争、改变游戏规则的能力，这也就是谷歌、亚马逊和“无绪”公司取得的成就。

此外，鼓励他人使用自己的设计直觉。这么做极具感染力，很能激发人的灵感。了解他人对一种设计或市场认识有什么样的感觉，并深入地挖掘一下。他们的感觉到底从何而来？对很多人来说，直觉是一种很难表达的东西，还有不少人没有信心表达自己的这种特质。一定要支持人们的直觉思维，不能用过度的分析去打压。要积极。要欢迎“异类”。

多向四周打量打量。创新总是发生在边缘，发生在内外接壤的边界上。在那里，有人利用直觉打破了标准模式，做出了与众不同的事情。

#巧取而不是模仿#不成熟的创新者模仿，成熟的创新者巧取。找到好点子很容易，可是让这些点子契合市场，这才是要下苦功夫的地方。

观察你的整个业务，把所有可能存在积极或消极影响都写出来：产品、包装、运输、消费者要扔掉的外包装、垃圾桶或垃圾场的旧产品、网站、制服、卡车、客户服务人员，所有这一切。特别要注意你平常不会去想的地方，那里往往蕴涵着最大的机遇。

#做自己产品最挑剔的用户#只有跳进河里，亲自感受水流的推力，你才能觉察到它其实并不总是朝一个方向推进。现实总是不止一个真相。先从亲自使用自己公司的产品入手，接着使用竞争对手们的产品。

#个人智商≠组织智商#组织也有智商，组织的智商并不等于首席执行官的智商，也不等于高级管理人员的平均智商。组织的整体智商是建立在谁与谁存在关联、怎样关联上。拆掉组织内部的部门封锁线，砸开组织通往外部世界的高墙，让人人都来参与合作。

让组织的每位成员都知道正在进行的所有活动，是整个组织变得更聪明的办法，而且它最简单，最快捷。

许多组织并不缺乏了不起的创新思想，也不是没有创新的意愿；相反，组织内封闭和毫无活力的流程才是路障。这些组织创建的流程变得过于制度化过于专业化，最终形成了自我封闭的僵化地基。营销部不能跟财务部沟通，财务部不能跟产品设计部沟通。这样的日子已经是过去时了。要让人人参与合作，你必须拆掉高墙。

