#+title: 大数据时代

生活、工作与思维的大变革(Big Data:A Revolution That Will Transform How We Live, Work, and Think)

   - 一场生活，工作与思维的大变革
     - 大数据，变革公共卫生
     - 大数据，变革商业
     - 大数据，变革思维
     - 大数据，开启重大的时代转型
     - 预测，大数据的核心
     - 大数据，大挑战
   - 大数据时代的思维变革
     - 更多，不是随机样本，而是全部数据
       - 让数据“发声”
       - 小数据时代的随机采样，最少的数据获得最多的信息
       - 全数据模式，样本=总体
     - 更杂，不是精确性，而是混杂性
       - 允许不精确
       - 大数据的简单算法比小数据的复杂算法更有效
       - 纷繁的数据越多越好
       - 混杂性，不是竭力避免，而是标准途径
       - 新的数据库设计的诞生
     - 更好，不是因果关系，而是相关关系
       - 林登与亚马逊推荐系统
       - 关联物，预测的关键
       - “是什么”，而不是“为什么”
       - 改变，从操作方式开始
       - 大数据，改变人类探索世界
   - 大数据朝代的商业变革
     - 数据化，一切皆可“量化”
       - 莫里的导航图，大数据的最早实践之一
       - 数据，从最不可能的地方提取出来
       - 数据化，不是数字化
       - 量化一切，数据化的核心
       - 当文字变成数据
       - 当方位变成数据
       - 当沟通变成数据
       - 世间万物的数据化
     - 价值，“取之不尽，用之不竭”的数据创新
       - ReCaptcha与数据再利用
       - 数据的“潜在价值”
       - 数据创新1：数据的再利用
       - 数据创新2：重组数据
       - 数据创新3：可扩展数据
       - 数据创新4：数据的折旧值
       - 数据创新5：数据废气
       - 数据创新6：开放数据
       - 给数据估值
     - 角色定位，数据，技术与思维的三足鼎立
       - decide.com与商品价格预测
       - 数据价值链的3大构成
       - 大数据掌控公司
       - 大数据技术公司
       - 大数据思维公司和个人
       - 全新的数据中间商
       - 专家的消亡与数据科学家的崛起
       - 大数据，决定企业竞争力
   - 大数据时代的管理变革
     - 风险，让数据主宰一切的隐忧
       - 无处不在的“第三只眼”
       - 我们的隐私被二次利用了
       - 预测惩罚，不是因为“所做”，而是因为“将做”
       - 数据独裁
       - 挣脱大数据的困境
     - 掌控，责任与自由并举的信息管理
       - 一切管理规范的变革
       - 管理变革1：个人隐私保护，从个人许可到让数据使用者承担责任
       - 管理变革2：个人动因 VS 预测分析
       - 管理变革3：击碎黑盒子，大数据算法师的崛起
       - 管理变革4：反数据垄断大亨
   - 正在发生的未来

大数据价值链的3大构成。根据所提供价值的不同来源，分别出现三种大数据公司。这三种来源是指：数据本身，技能与思维。
   - 第一种是基于数据本身的公司：这些公司拥有大量数据或者至少可以收集到大量数据，却不一定有有从数据中提取价值或者用数据催生创新思想的技能。
   - 第二种是基于技能的公司。它们通常是咨询公司，技术供应商或者分析公司。它们掌握了专业技能但并不一定拥有数据或提出数据创新性用途的才能。
   - 第三种是基于思维的公司。对于某些公司来说，数据和技能并不是成功的关键，让这些公司脱颖而出的是其创始人和员工的创新思维，他们怎么样挖掘数据的新价值的独特想法。

大数据也为小公司带来的机遇。聪明而灵活的小公司能够享受到非固有资产规模带来的好处。这也就是说，它们可能没有很多的固有资产但是存在感非常强，也可以低成本地传播它们的创新成果。重要的是，因为最好的大数据服务都是以创新思维为基础的，所以它们不一定需要大量的原始资本投入。数据可以授权但是不能被占有，数据分析能在云处理平台上快速而且以低成本地进行，而授权费则应从数据带来的利益中抽取一小部分。不过，大数据对于中等规模的公司帮助并不大。超大型的公司占据了规模优势，而小公司则具有灵活性。在传统行业中，中等规模的公司比大公司更有灵活性，比小公司更具有规模性。但是在大数据时代，一个公司没必要非要达到某种规模才能支付它的生产设备所需投入。大数据公司发现它们可以是一个灵活的小公司并且会很成功（或者会被大数据巨头并购）

也许，大数据预测可以为我们打造一个更安全，更高效的社会。但是却否定了我们之所以作为人的重要组成部分，自由选择的能力和行为责任自负。大数据成为了集体选择的工具，但也放弃了我们的自由意志。大数据的不利影响斌不是大数据本身的缺陷，而是我们滥用大数据预测所导致的结果。大数据的决策是建立在相关性基础上的。让人们为还未实施的未来行为买单是带来不利影响的主要原因，因为我们把个人罪责判定建立在大数据预测的基础上是不合理的。

在由“小数据”时代向大数据时代转变的过程中，我们对信息的一些局限性必须给予高度的重视。数据的质量可能会很差；可能是不客观的；可能存在分析错误或者具有误导性；更糟糕的是，数据可能根本达不到量化它的目的。我们比想象中更容易受到数据的统治，让数据以良莠参半的方式统治我们。其威胁就是，我们可能会完全受限于我们的分析结果，即使这个结果理应受到质疑，或者说我们会形成一种对数据的执迷，因而仅仅为了收集数据而收集数据，或者赋予数据根本无权得到的信任。

其实，卓越的才华并不依赖于数据。史蒂夫乔布斯多年来持续不断地改善Mac笔记本，依赖的可能是行业分析，但是他发行的iPod，iPhone，和iPad靠的就不是数据，而是直觉，他依赖于他的第六感。当记者问及乔布斯苹果推出iPod之前做过了多少市场调研时，他那个著名的回答是这样的：“没做！消费者没义务去了解自己需要什么。”

大数据并不是一个充斥着运算法则和机器的冰冷世界，其中仍需要人类扮演重要角色。人类独有的弱点和，错觉，错误都是十分必要的，因为这些特性的另一头牵着的是人类的创造力，直觉和天赋。偶尔也会带来屈辱或固执的同样混乱的大脑运作，也能带来成功，或在偶然间促成我们的伟大。这提示我们应该乐于接受类似的不准确，因为不准确正是我们之所以为人的特征之一。就好像我们学习处理混乱数据一样，因为这些数据服务是更加广大的目标。毕竟混乱构成了世界的本质，也构成了人脑的本质。而无论是世界的混乱还是人脑的混乱，学会接受和应用它们才能得益。
