#+title: 谷歌是如何运营的(How Google Works)

大多数人并没有接触过这种如登月般异想天开的思维方式，他们习惯用“不可能”来否定自己的想法，而不是从基本物理原则出发去探索可能性。

如果我们把传统知识工作者与谷歌十几年来招徕的工程师等人才放在一起对比，就会发现谷歌的人才是一个截然不同的员工群体。这些人并不拘泥于特定的任务，也不受公司信息和计算能力的约束。他们不惧怕冒险，即便在冒险中失败，也不会受到惩罚或牵制。他们不被职位头衔或企业的组织结构羁绊住手脚，甚至还有人鼓励他们将自己的构想付诸实现。如果出现不同意见，他们不会选择缄口不言。他们很容易失去耐心，经常变换职位。他们具有多领域的能力，经常会将前沿技术、商业头脑以及奇思妙想结合在一起。换句话说，至少从传统意义上来说，这些人已经不能算是知识工作者了。这是一个新的物种，我们称之为“创意精英”，他们，便是互联网时代取得成功的关键所在。

企业文化一旦形成，想要改变绝非易事，因为企业在成立之初容易受“自我选择倾向”的影响。也就是说，与企业秉持相似理念的人会被吸引而来，而与企业理念相左的人则不会。

先思考一下你理想中的企业文化或现有的企业文化。然后，让我们把时间快进几个月或几年，想象一下这样一个场景：一位员工为了一个困难的抉择纠结许久，一直熬到深夜。25他走到厨房里去拿一杯咖啡，回想起企业的价值观。这些价值观，领导在会议上传达过，同事们在午餐休息时议论过，德高望重的公司前辈也身体力行过。那么对于这位员工或者所有员工而言，这些企业价值观应当简明扼要地阐述出企业最为重视什么以及企业成员最为关注什么。否则，这些价值观宣言就毫无意义，根本无法帮助创意精英们做出正确的抉择。

而我们的理念则完全相反，我们认为，办公状态应鼓励大家多多交流，让大家在喧闹拥挤的办公室里畅所欲言、激情碰撞。在参与完团队活动后，员工可以到清静之地换换脑子。正因如此，谷歌的办公室里设置了许多休闲设施：咖啡馆和小型厨房里有僻静的位子，另外还有私密的会议室、露天阳台和院落，甚至还有睡袋呢。然而，休整完毕后，他们应当回到同事中间继续办公。

但正如乔纳森常说的，在家办公其实无异于一种会在整个公司内蔓延、让员工士气萎靡不振的瘟疫。已故的贝尔实验室前董事长默文·凯利就是本着鼓励员工相互沟通的理念来设计公司办公格局的。34走过长长的走廊，贝尔实验室的工程师和科学家们要么会与同事打个照面，要么就直接被拽进某间办公室里去了，而这种偶遇的机会是在家办公者绝对不会碰到的。

一条至关重要的组织原则是：找出最有影响力的人物，组织就以此人为中心。不要把岗位或经验作为选择管理者的标尺，而要看他的表现和热情。

不”对于创意精英而言犹如当头一棒，这表明企业已然失去成立之初的活力，披上了过于形式化的外衣。在遭遇一次次“不”的重重打击后，创意精英们便不再多费口舌，开始盘算另谋高就了。

一家初创的伟大企业、一个炙手可热的项目或者一份好工作，都应该充满乐趣。如果你忙得焦头烂额，却没收获快乐，那就有问题了。对未来成功的憧憬会令人振奋，但更多的乐趣却来自同事间的欢声笑语、幽默调侃。

但我们敢百分百地打包票：如果你有商业计划，那你的计划一定是错误的。只要是MBA式的商业计划，无论经过怎样的深思熟虑，一定在某些方面存在硬伤。如果你硬要一心一意按照这份有瑕疵的计划一步步走下去，那么就会像企业家埃里克·莱斯说的一样“实现失败”。54因此，风险投资家应永远遵守投团队而不投计划的准则。既然计划会错，那么人就得对。成功的团队懂得如何发现计划中的瑕疵，并及时做出调整。

计划的无常可能会让一些想加入团队的人望而却步，因为绝大部分人都不喜欢不确定性。而创意精英与一般人不同，他们就爱自己动脑筋想对策。

不断改进以及使用巧妙的商业手段无可厚非，但如果把市场调查看得比技术创新还要重要，那就本末倒置了。大多数企业都是以技术洞见为基础起步的，但在前进的路上却往往偏离了航道（这就是舍本逐末）。

如果你把注意力放在竞争对手身上，那你绝不会实现真正的创新。当你与竞争对手为了市场占有率的几个百分点争得不可开交时，半路往往会杀出一个不在乎市场占有率的竞争者，用全新的平台颠覆整个游戏。

想要留住创意精英，最好的方法就是避免让他们太过安逸，而是不断用新的想法保持他们工作的趣味性。

假如你在走廊里遇到了上司的上司，他询问你正在做什么项目。好吧，我们就假设你遇到的是首席执行官吧。那么，你会如何作答呢？首席执行官可不是在跟你寒暄：现在就大声说出你的回答。快点，你只有30秒。

思考一下，5年之后，你理想中的工作是什么样的。你想做什么样的工作？想要什么样的收入？描述一下你心目中的理想职位：如果你在网上看到了这份工作的招聘信息，那么这广告具体会是什么样的呢？现在，把时间快进四五年，假设自己已经得到了这份工作。那么，你5年后的简历会是什么样的？想要得到5年后心中理想的位置，你从现在起需要如何选择前面的路？

谷歌于2004年上市以来，我们每一季度都会把致董事会信函与大家分享，迄今为止，还没有出现信息泄漏问题。另外，也没有人因为缺少对公司总体情况的了解而提出过抱怨。就算有人抱怨，我们只要让当事人读一读致董事会信函、看一看埃里克的演讲就行了。

在生活中，很多情况下一件事情需要重复大约20遍才能被人真正听进去。143如果你只重复几遍，对方会因为忙碌而充耳不闻。多重复几遍，他们才能感受到耳边隐约有动静。等到重复了15~20遍的时候，你自己可能都懒得说了，而这时，听者才刚刚开始有所触动。因此，作为领导者，你必须习惯于苦口婆心、诲人不倦。埃里克喜欢说：“祷文不会因重复而失色。”
