#+title: 闻香识女人(Scent of a Woman)

Frank: I’ll show you out of order. You don’t know what out of order is, Mr. Trask, I’d show you, but I’m too old, I’m too tired, I’m too ****in’ blind, if I were the man I was five years ago, I’d take a flame thrower to this place! Out of order? Who the hell do you think you’re talkin’ to? I’ve been around, you know? There was a time I could see, and I have seen, boys like these, younger than these, their arms torn out, their legs ripped off, but there is nothin’ like the sight of an amputated spirit. There is no prosthetic for that, you think you’re merely sendin’ this splendid foot solider back home to Oregen with his tail between his legs, but I say you’re executin’ his soul! And why? Because he is not a Baird man. Baird men, you hurt this boy, you’re gonna be Baird bums, the lot of you. And Harry, Jimmy, and Trent, wherever you are out there, **** you too!

斯莱德中校：让你见识见识什么是破坏规矩，你不知道什么叫破坏规矩，垂斯克先生，真该让你见识，可我太老了，太累了，我他妈的还是个瞎子。要是五年前，我会拿火焰喷射剂把这给烧了！破坏规矩？你以为在跟谁说话？我可是久经沙场，那时候我还能看得见，我看见的是象他们这么大，甚至还要小孩子们胳膊被炸断了，腿被截肢了，可但那些都不及丑陋的灵魂可怕，因为灵魂没有义肢。你以为你只是把这个好青年像落水狗一样的送回俄勒冈的老家？？你们泯灭的是他的灵魂！！为什么？！就因为他不够做一个拜尔德人？拜尔德人，你们若是伤害了这个孩子，你们就是拜尔德的混蛋，你们全是。哈瑞、吉米、特伦特，不管你们坐在哪，见你们的鬼！

Frank: I’m not finished. As I came in here, I heard those words: cradle of leadership. Well, when the bough breaks, the cradle will fall, and it has fallen here, it has fallen. Makers of men, creators of leaders, be careful what kind of leaders you’re producin’ here. I don’t know if Charlie’s silence here today is right or wrong, I’m not a judge or jury, but I can tell you this: he won’t sell anybody out to buy his future! And that my friends is called integrity, that’s called courage. Now, that’s the stuff leaders should be made of. Now I have come to crossroads in my life, I always knew what the right path was. Without exception, I knew, but I never took it, you know why, it was too damn hard. Now here’s Charlie, he’s come to the crossroads, he has chosen a path. It’s the right path, it’s a path made of principle that leads to character. Let him continue on his journey. You hold this boy’s future in your hands, committee, it’s a valuable future, believe me. Don’t destroy it, protect it. Embrace it. It’s gonna make you proud one day, I promise you.

斯莱德中校：我还没说完呢，我刚一进到这里，就听到那些话：”未来领袖的摇篮”。如果架子断了，摇篮也就掉了，它已经随落了。造就青年、培养未来的领袖的人们，看吧！要小心了，你们在培养什么样的领袖，我不知道！今天查理保持沉默是对还是错，我虽然不是法官，但我可以告诉你，他不会为了自己的前途而出卖任何人。朋友们！这就是人们常说的正直，这就是勇气，这才是未来领袖所具有的品质。现在我到了一个人生的十字路口，我一向知道哪条路是正确的，毋庸置疑，我知道，可我从没走它，为什么？因为它太艰难了。轮到查理了，他也在一个人生的十字路口，他选择了一条路，一条有原则、成全他人格的路。让他沿着这条路继续前行吧，这孩子的前途掌握在你们的手里，委员们，他会前途无量的，相信我，别毁了他！保护他！支持他！我保证会有一天你们会为此而感到骄傲！我保证。
