#+title: 反脆弱: 从不确定性中获益

“黑天鹅”事件是造成广泛、严重后果的，不可预知的、不定期发生的大规模事件。对某些观察者来说，他完全没有预料到它们的发生，这种人通常被称为“火鸡”，因为他们对这些事件完全没有预期，并会受到这些事件的伤害。我已经说过，历史其实大部分源于“黑天鹅”事件，但我们关心的却是如何微调我们对普通事件的了解，因此我们不断地开发模型、理论或表述方式，可是，这些东西不可能跟踪“黑天鹅”事件，或者衡量这些冲击的发生概率。

“黑天鹅”事件绑架了我们的思维，让我们感到自己“差不多”或“几乎”预测到了它们，因为它们都是可以进行回溯性解释的。由于存在可预测性错觉，我们没有意识到这些“黑天鹅”事件对生活的影响。现实生活远比我们记忆中的生活更加错综复杂——我们的头脑倾向于将历史以更平稳和更线性的状态呈现出来，这导致我们低估了随机性。一旦我们看到随机事件时，就会心生畏惧并反应过度。在逃避这种恐惧以及对秩序的渴求中，一些人类建立的系统往往会打乱事物的隐性逻辑，或者打乱不那么明显的逻辑，结果导致“黑天鹅”事件的发生，而且几乎得不到任何收益。当你寻求秩序，你得到的不过是表面的秩序；而当你拥抱随机性，你却能把握秩序、掌控局面。

“黑天鹅”问题有一个恼人方面，实际上也是一个很核心的并在很大程度上被忽略的问题，即罕见事件的发生概率根本是不可计算的。我们对百年一遇洪水的了解远低于5年一遇的洪灾，其模型的误差在涉及小概率事件时会成倍增长。事件越罕见，越难以追踪，我们对其发生频率的了解就越少。然而，事件越罕见，参与预测、建模和在会议上用花哨的演示文件陈述其计算方程式的“科学家”们却显得越有信心。

得益于反脆弱性，大自然是管理罕见事件的最好专家，也是管理“黑天鹅”事件的高手；几十亿年来，它成功地演变进化到今天，而无须任何由常春藤盟校培养出来的，并由某个研究委员会任命的主任给出命令和控制指令。不仅仅是“黑天鹅”事件的解决方案，了解反脆弱性还会使我们从理智上不那么害怕接受一个事实：“黑天鹅”事件对历史、技术、知识以及所有事情的发展都有存在的必要。

与人们的观点相反，一个复杂的系统并不需要复杂的管理机制和法规，以及错综复杂的政策。事实上，越简单越好。复杂机制会导致意想不到的连锁反应。由于缺乏透明度，干预会导致不可预测的后果，接着是对结果中“不可预测”的方面致歉，然后再度出手干预来纠正衍生影响，结果又派生出一系列“不可预测”的反应，每一个都比前一个更糟糕。 然而，在现代生活中，简单的做法一直难以实现，因为它有违某些努力寻求复杂化以证明其工作合理性的人所秉持的精神。

不确定性、混乱和未知性是完全等价的：反脆弱性系统（在某种程度上）从上述所有事物中获益，而脆弱的系统则会从中受损，即使一些哲学家会告诉你说：“它们显然不是一回事。”这些哲学家虽然身处不同大学的不同教学楼，但你会发现他们有一个共性，即他们一生中从未承受过真正的风险，或者更糟糕的说法是，他们从未真正生活过。

过度补偿机制往往隐藏在最不可能的地方。长途飞行后最好去健身房锻炼以消除疲劳，而不是坐下来休息。此外，还有一个众所周知的小伎俩，如果你急着要完成某事，不妨将其交给办公室里任务最繁忙的（或第二繁忙的）那个人去做。大多数人的空闲时间都会被浪费掉，因为空闲时间会让他们无所事事、懒惰、无心向学，而一旦他们忙起来，他们往往会在其他任务上也更为积极。过度反应在这里再次显现。

他进行的是最高重量级别的训练，并极为推崇这种训练方法，因为他发现这是最有效和最省时的方法。该方法包括在健身房内先利用一小段时间专注于提高过去的举重纪录，也就是你曾举起过的最大重量，就像最高水位标记一样。这种锻炼以尝试超越纪录一两次为限，而不是把时间花在无聊而耗时的重复尝试上。这种训练让我想到了自然的举重方式，而且这符合循证文献：全力以赴做到极致，随后将剩余时间用于休息和享用巨无霸牛排上。如今，我进行极限训练的时间已经有4年了，我很惊喜地看到，我的生理状况如何在预期超越过去最佳状态的过程中不断改善，直至到达极限。
