#+title: 文明之光

-----
地球的历史

| 日期        | 距离今天的时间（年） | 大事                       |
|-------------+----------------------+----------------------------|
| 1.1         | 45.3亿               | 月亮形成/地球形成          |
| 1.11        | 44亿                 | 液态水形成                 |
| 1月底       | 38~42亿              | 海洋形成                   |
| 2月初       | 40亿                 | 超分子出现(可以自我复制)   |
| 2月底       | 38亿                 | 古菌出现                   |
| 3月中       | 36亿                 | 光合作用的细菌出现         |
| 7月初       | 18亿                 | 复杂的单细胞生物出现       |
| 9月中       | 10亿                 | 多细胞生物出现             |
| 11月中      | 6亿                  | 海藻和海绵出现             |
| 11月下旬    | 5.4亿                | 寒武纪生物大爆发           |
| 12月初      | 4.2亿                | 脊椎动物出现               |
| 12月中      | 2.5亿                | 二叠纪-三叠纪生物大灭绝    |
| 12月中      | 2.3亿                | 恐龙出现                   |
| 12.15       | 2亿                  | 被子植物出现，恐龙主宰地球 |
| 12.26       | 6500万               | 恐龙灭绝，哺乳动物兴起     |
| 12.30       | 1500万               | 古猿出现                   |
| 12.31-17:00 | 350万                | 人类出现                   |
| 12.31-23:30 | 25万                 | 现代人出现                 |
| 12.31-23:52 | 7万                  | 现代人走出非洲             |
| 12.31-23:56 | 3万                  | 人类称为地球主宰           |
| 12.31-23:59 | 1万                  | 文明开始                   |

-----
近代自然科学的很多体系都是在古希腊时代奠定的，希腊人在学术研究上有别于东方文明之处，不在于一两项科学发明和发现，而在于它们将自然科学各学科分门别类，对每个学科都建立起一整套系统的体系，在此基础上，演绎或归纳出普遍规律性，即定理或定律，继而成为自然科学各个学科的基石和支柱。后人可以在前人发现的基础上继续研究，推动科学的发展。无论是古希腊奠定的几何学，天文学和物理学，还是后来笛卡尔发明的解析几何或者牛顿发明的微积分，无不遵循古希腊人建立科学学科分支的办法。反观东方文明，在科学研究上有两大缺陷，首先是缺乏完整的理论体系；其次常常会将问题和定理定律混为一谈，虽然他们的解答和证明过程可能类似。这样一来，后人就很难继承前人的工作，几乎所有的研究都得从头再来，导致几千年来在科学研究上的原地踏步。事实上，中国清代的数学家估算圆周率并不比祖冲之更准确，而19世纪阿拉伯最好的数学家也未必掌握了他们祖先1000年前的数学发现。

-----
欧洲人在瓷器制造上超越亚洲人，则是整体科技进步和工业化的成果。欧洲人较早地掌握了现代的科学研究方法，擅长定量分析和比较试验，因此完全弄清楚了瓷器的成分和烧制的原理。在研制过程中，他们保留了全部的原始数据和实验报告，这样，每取得一点进步，后人都可以直接收益。这种科学研究的方法是欧洲人取得长足进步的基础。相比之下，中国工匠更多的是具有对制瓷工艺的感性认识，他们靠“师傅带徒弟”的方法将经验代代相传，而徒弟能够超越师傅，则完全靠悟性。中间即使有一些发明和改进，却因为没有详细的过程记载，或者是出于保密故意不记载，很多发明和改进都无法传世，比如宋代五大名窑的制作工艺大多失传了。这样，后世常常不得不重复前人的失败，使得瓷器制造技术进步缓慢。这其实不是中国瓷器制造特有的问题，而是中国古代很多手工业普遍存在的现象。

-----
创造亚当（创世纪，米开朗基罗）

file:../images/adam-creation.jpg

-----
查理一世耶批准了麦哲伦的计划，并且给了他和他的合伙人非常“慷慨的”特权，其中包括：
- 垄断所发现的航线10年的使用权
- 任命麦哲伦为他所发现的土地的总督，并可以从未来的收益中提成5%
- 此次航海贸易的五分之一的利润
- 所发现海岛（除了前六个最大的）今后受益的十五分之一
我之所以把这些条款都列出来，是因为这类条款鼓励了欧洲人去冒险。相对来讲，当时东方帝国的皇帝们给于功臣的常常不是一起分享的利益，而是杀戮。要了解近代西方人为什么能够在落后几百年的情况下崛起，并且超越了亚洲国家，这些契约是解开秘密的一把钥匙。

-----
哥伦布，达伽马和麦哲伦无疑是人类历史上最伟大的航海家，他们和当时无数的冒险家一道，开启了大航海的时代。它们各自的航行在历史上的作用各不相同：哥伦布发现了新大陆，达伽马找到了从东绕过非洲到达亚洲的航线，麦哲伦（和埃尔卡诺）第一次完成了人类的环球航行，并且开启了往西经过美洲到达亚洲的航线。他们三个人在出发前都犯了同样的错误，低估了他们即将进行的探险的难度：哥伦布把一万多海里的航行估计成两千多海里，达伽马也少算了百分之六十的航程，而麦哲伦则信息完全错误，误把河口当做了海峡，以至于航程比预想的至少多了一年的时间。或许正因为如此，他们才壮起了胆子去做当时人们想都不敢想的事情，从这方面来讲，他们都是幸运的。

-----
“先生们，如果让我必须在那种由老师管着，修足学分就能毕业的大学与那种没有教授和考试让年轻人一起共同生活，互相学习三四年的大学中选择一种，我讲毫不犹豫地选择后者。为什么呢？我是这样想的：当许多聪明，求知欲强，富有同情心且目光敏锐的年轻人聚到一起，即使没有人教，他们也能互相学习。他们互相交流，了解到新的思想和看法，看到新鲜事物并且掌握独到的行为判断力。”

牛顿在化学上的贡献，有点像达芬奇在物理学上的贡献，他们都通过大量的实验注意到很多自然现象并且总结出一些规律，但是由于认识的不足，无法给出科学的解释，或往往给出的一些错误的结论。由于认识的局限性，牛顿没有成为一位合格的化学家，他寻求的目标（炼金）在化学上是做不到的，但是他的研究方法却是可取的。 在科学研究上，正确的方法比正确的结论更加重要，因为如果方法正确，即使一时得不到正确的结论，但是只要按照正确的方法走下去，最终可以得到正确的结论。但是如果方法不正确，偶然得到一些正确的结论，对科学的发展却没有什么积累。

-----
成千上万的荷兰人敢于把自己的积蓄投入这项冒险，原因有这么几条。首先荷兰人喜欢冒险，这也使得他们的后裔建立起了华尔街。其次东印度公司有荷兰政府的背书。再次，但也是最重要的是，荷兰商人信誉良好，并且是世界上最早恪守信托责任的群体。信托责任并不是人们常说的守信用和不欺诈那么简单，它至少包括三方面的责任，首先是法律责任，这个很容易理解，当集资人把钱交给某个人做生意时，这个人有法律上的义务，不能将这些钱窃为己有。第二是道德责任，比如合伙人将公司交给职业经理人管理，经理人有责任将公司管理好，并且为公司股东谋求利益。一个管理者，如果不尽心尽力为股东谋求利益（可以是短期，也可以是长远的），也许并不违反法律，但是不符合道德责任。第三是专业责任，受托人必须具有专业知识和技能，这一点其实常被人们忽略，没有第三点，好心未必能做成好事。信贷责任不仅是现代管理的基础，也是现代商业的支柱。

荷兰船员在生命和信托责任之间，选择了恪守信托责任，也创立了传之后世的的商业法则。这种行为在那些信奉“人不为己，天诛地灭”的国度是难以置信的，但这又实实在在地发生在几百年前的荷兰。这种恪守信托责任的行为，日后给荷兰商人们带来了长远的利益，它帮助荷兰商人占领了海上贸易的世界市场。巴伦支也在这次探险中丧生，为了纪念他和他的同伴对探索北极航线做出的贡献，后世用他的名字命名了北冰洋的一片海域。

-----
美国的立国，是人类历史上第一次通过协商而非武力解决纠纷，从而达成一致，最终建立起一个多民族统一的国家。美国立宪谈判之所以能够成功，当然需要一定的社会条件。首先是法国的启蒙运动使得民主思想在美国普遍被接受，其次是各个利益集团的代表们开明温和的价值取向。这些国父虽然文化背景不同，教育程度不同，身份和利益不同，但是没有希望使用武力解决问题。美国的立宪过程从1787年5月到1788年6月，讨论和争论了一年多的时间，多次面临谈不下去的困境，但是代表们坚持一个原则，就是可以谈判，但是不能动武。在制宪会议上，代表们遇到一个又一个矛盾，他们解决问题靠的是妥协和宽容。没有一位代表对对最后的结果完全满意，用富兰克林话说：“我得承认我自己对这部宪法中的好几个部分并不认同，但是我不觉得我会阻止其通过...我们即使再开几次制宪会议也未必能够制订出一部更好的宪法...所以先生们，尽管这让我自己也感到意外，但我认为这个系统已经接近完美....”但是，这样的结果却是代表们（和他们所代表的州）都能接受。在美国的立宪过程中，我们看到了人类的进步，看到人们学会用文明的方式和理性的力量建立一个国家。

和历史上很多强大的国家不同的是，美国是一个松散的联邦，而这个联邦日后不仅没有分裂，反而成为超级大国。这当然是很多代美国人长期努力的结果，但是从另一个方面讲，也和这些开国者为了这个国家确立了良好额政治体制和树立了无私的道德规范有关。当初，这些开国元勋谁也没有把自己当回事，更没有把自己当成什么开国的伟人，但是历史证明这些没有把自己当回事的国父，反而在后世成为了当代政治家学习的典范。

-----
炼金术士的另一个贡献，就是定量分析这种实验的结果，量杯，天平，比重计和各种简单的测量工具被用于他们的实验，有了这些定量的记录和分析，后人便可以重复前人的实验结果。这一点成为了后世人们进行科学研究的一个基本方法。要想在前人的基础上改进，第一步都是要重复前人的实验结果，这是今天在西方科学杂志和高等级的学术会议上发表论文的铁律。比如，一个人发明了一种更准确的指纹识别算法，如果他只是给出自己新算法的准确率，而没有对比前人发明的算法在同等条件下取得的结果，任何权威杂志都不会录用他的论文。定量分析带来的另一个结果就是，在科学上从尊重权威变成尊重事实。

-----
上述原因说到底是一个“利”字，作为一个企业家，爱迪生必须让自己的企业活下来，然后才可能有所发展，而不是说“哦，交流电好，大家用交流电吧，我的企业生死无关紧要”。
