#+title: Do not go gentle into that good night

#+BEGIN_VERSE
Do not go gentle into that good night, 不要温和地走进那个良夜,
Old age should burn and rave at close of day; 白昼将尽,暮年仍应燃烧咆哮;
Rage, rage against the dying of the light. 怒斥吧,怒斥光的消逝。

Though wise men at their end know dark is right, 虽然在白昼尽头,智者自知该踏上夜途, 　　
Because their words had forked no lightning they 因为言语未曾迸发出电光,他们
Do not go gentle into that good night. 不要温和地走进那个良夜。 　　

Good men, the last wave by, crying how bright 好人,当最后一浪过去,高呼着他们脆弱的善行
Their frail deeds might have danced in a green bay, 本来也许可以在绿湾上快意地舞蹈,
Rage, rage against the dying of the light. 所以,他们怒斥,怒斥光的消逝。 　　

Wild men who caught and sang the sun in flight, 狂人抓住稍纵即逝的阳光,为之歌唱,
And learn, too late, they grieved it on its way, 并意识到,太迟了,他们过去总为时光伤逝,
Do not go gentle into that good night. 不要温和地走进那个良夜。 　　

Grave men, near death, who see with blinding sight 严肃的人,在生命尽头,用模糊的双眼看到
Blind eyes could blaze like meteors and be gay, 失明的眼可以像流星般闪耀,欢欣雀跃,
Rage, rage against the dying of the light. 所以,他们怒斥,怒斥光的消逝。　　

And you, my father, there on the sad height, 而您,我的父亲,在生命那悲哀之极,
Curse, bless, me now with your fierce tears, I pray. 我求您现在用您的热泪诅咒我,祝福我吧
Do not go gentle into that good night. 不要温和地走进那个良夜。
Rage, rage against the dying of the light. 怒斥吧,怒斥光的消逝。
#+END_VERSE
