#+title: 股票作手回忆录

实战操作和虚拟操作的最大区别就是，同一个人的智商和情商都会急速降低或提升，以至于你都认不出还是那个人，其实这才是真正的他。

在信息不全的条件下当机立断也很重要，在股市上，你不可能把所有的事情都弄得清清楚楚明明白白再采取行动，因为那时候对赚钱来说已经为时已晚。

这是一个人的游戏。你为什么要告诉别人你在做什么？是为了拖他下水还是为了拖他下水？

乐意不乐意承担风险是投机业中的道德标准。能接受成功也能面对后果的投机客，便是有道德的；能接受成功却不能面对后果，就是不道德的。

限价交易只是我在空壳证券公司使用的方法，根本无法在大型证券公司采用。如果不是这样，我可能永远学不会真正的股票投机，只能根据自己浅陋的经验继续赌博。

判断对错并不重要，重要的在于正确时获取了多大利润，错误时亏损了多少。

不要相信投资专家的任何建议，不要相信所谓的内幕消息，不要相信证券公司的推荐，不要相信"至少不会损失"的鬼话，你只能相信自己的研究。

如果市场总是可有效预测的，我只会成为一个在大街上手拎马口铁罐的流浪汉。

在家乡，我能够平心静气地思考自己之前的一些愚蠢操作，隔一段距离与时间，你总能更清楚地看透事情的原委。所以，下次再去纽约，我一定能做得更好。

可我听了老行家的忠告，抑制了年少的冲劲，决定学聪明点，保守而谨慎地操作。众所周知，保守而谨慎的操作方法就是获利落袋为安，然后静待回档低吸。我就是这么干的，于是常常守着赚到的4个点的收益，等着股价回落，却眼睁睁地看着它继续上涨10个点，偶尔回踩。人们常说：获利落袋，必能敛财。但在牛市里赚4个点就急着套现的人永远也发不了大财。 本来可以赚2万美元，我却只赚了2000块，这就是我的保守主义带给我的回报。

我终于明白，当老帕特里奇一直告诉其他客户"啊，你知道的，现在可是牛市啊"时，他真正的意思是说，赚大钱不能靠股价的短期波动，而要靠大波动。换句话说，不能光看个别的起伏，而要判断个股的大趋势和大盘的行情走势。明白了这个道理，我又向前迈进了一大步。

现在，让我告诉你，在华尔街摸爬滚打了这么多年，累计输赢了几百万之后，我要告诉你：我的想法从来都没有替我赚过大钱，总是坚持不动替我赚大钱，明白吗？是我坚持不动！看对个股波动没什么了不起。你能在股市发现很多高手，看时机很准，总能在最佳利润点买卖股票，但他们都没能真正赚到钱。为什么呢？能看对波动方向的人很多，能看对波动并坚持不动的人才真正厉害。但是，一个股票投资者只有牢牢掌握了这个诀窍才能赚大钱。而这是最难学的。

不要去抓最初或最后的1/8点利润，那需要太大的代价。多少股票投资者为了抓住这1/8点利润付出了好几百万块的代价，这些钱都足以建一条横跨美洲大陆的水泥公路了。

投资者必需着眼于价格水平与潜在或核心价值的相互关系，而不是市场上正在做什么或将要做什么的变化。

当你经常去歌剧院而不研究股市的时候，那也就说明你不属于这个游戏了。

如果牌过三巡，你还不知道谁是牌桌上的傻瓜，那么你就是那个傻瓜。

当有机会获利时，千万不要畏缩不前。做对还不够，要尽可能多地获取。

地震发生的头一两天，华尔街并不关注这场灾难，他们会说这是因为首批报道的内容并不太严重，我倒认为这是因为改变大众的观点需要一个漫长的过程，甚至职业交易商也经常表现得反应迟钝、目光短浅。

我发现纸上谈兵比实际交易容易得多，有些家伙说话的口气真让人受不了。

持有一只股票，期待它每个早晨都上涨是十分愚蠢的。

生命总是迸发于混乱的边缘，所以，在混乱的状况中生存是我最擅长的。

朋友问他为什么睡不着，他说因为手上的棉花期货太多，一想到这些棉花他就睡不着，他精疲力竭。他问朋友该怎么办。朋友建议他卖点儿，卖到能睡觉为止。

股价下跌永远不是买入股票的理由，因为可能会跌得更低。

普通人总觉得自己的操作只是游戏，而且自以为是，从而导致思考不深刻、不透彻；专业人士则力求行事正确，这比赚钱更重要，因为他们知道只要做对每一件事，自然能赚到钱。投机者应该向职业大玩家学习，高瞻运瞩而不是只看到眼前利益。

如果总是做显而易见或大家都在做的事，你就赚不到钱。对于理性投资，精神态度比技巧更重要。

再聪明的投资者也可能需要坚强的意志才能置身于"羊群"之外。

我得到了另外一个代价惨重的经验：一个人犯错不需要理由。几百万美元还换来了另外一个经验：对交易者来说，最危险的敌人就是聪明的朋友的热切规劝和人格魅力。

卖出有盈利的股票，保留亏损股票，就像把花园里的花拔掉，而去灌溉野草一样；股市就像玩扑克牌，只要手里的牌显示有可能赢，就要紧紧握住。

欠别人的钱，我可以用钱去还，但是我必须用同样的方式去偿还人情和善意，而你很容易发现这些人情账有时候是非常昂贵的，而且你不知道还到什么时候才算完。

所以，我的情感再一次胜过了理智，我让步了。我让自己的判断臣服于他的意愿，这就是我毁灭的原因。任何一个正派的人都有感恩之心，但是人不应该被这样的感情牵绊。毁灭的开始就是我不但亏掉了所有的利润，还欠了公司15万美元的债务。我觉得很难过，可丹让我不必担心。

作为一般人，我在丹·威廉森公司的做法无可厚非。但身为一个投机者，我任凭违背自己判断的看法影响操作，真是太不应该太不明智了。感恩是一种美德，却不该在股市上履行，因为你对别人侠义忠诚，行情可不会对你侠义，也不会奖励你的忠诚。但我意识到自己当时只能那么做，我不会仅仅为了能在股市上交易就改变自己懂得感恩的本性。不过生意终究是生意，作为一个投机者，我应该始终坚持自己的判断。

我远离威廉森与布朗公司。我的意思是说，连续六周，我一心研读行情，刻意不去他们公司。我担心一旦我去了那里，知道自己可以买500股，就可能禁不住诱惑，在不正确的时间交易不适当的股票。交易商除了要研究基本形势、牢记市场先例、考虑大众心理、了解证券商的限制之外，还必须认识并防范自身的弱点。你大可不必和自己身上的人性弱点生气。我发现解读自己和解读行情同样重要。我研究了自己，知道活跃市场会对自己产生不可避免的诱惑，知道自己看到某些市场动态时会忍不住出手。我研究自己弱点时怀有的情绪和心情，就像我分析作物行情和收益报告时怀有的情绪和心情一样，客观而冷静。

绝对不要妄图在最高价抛出，在最高点逃顶的心理是不明智、不健康的。如果没有上涨空间确定要抛出了，就在回档的第一时间抛出。

承认错误是件值得骄傲的事情。我能承认错误，也就会原谅别人犯错。这是我与他人和谐共事的基础。犯错误并没有什么好羞耻的，只有知错不改才是耻辱。

对于听信内幕消息的蠢货，我们还能说什么呢？人们听信内部消息，不是因为他们太蠢，而是像我所说的那样，他们喜欢沉溺于希望之中。

只有在得到对企业的定性调查结果的支持的前提下，量化的指标才是有用的。

如果你是一遇见什么事儿就慌着脱手的人，就该远离股票市场。

经验能教会人很多事情，违背经验行事就是重复交学费，而且会败得很惨。违背常识行事更是不应当。但不是只有外行才会成为华尔街傻瓜。

普通人总是不考虑股票真正的价值，而只考虑现实的价格，他们的行为受控于恐惧而不是市场形势。此时，这些人就采取了最容易的方法——相信这只股票会一直涨下去。这就是为什么这些外行虽然知道不应该在最高价买进，却总在最高价买进故而赔得一塌糊涂的原因。繁荣时期，广大股民总能获得高额账面利润，不过，这些利润却永远停留在了账面上，无法套现。

股民们应该铭记这一点：股价长期低迷的原因绝不会是空头掼压。一旦某只股票持续下跌，你可以肯定其中一定有问题，不是市场有问题，就是公司本身有问题。如果这种下跌没有道理，价格很快就会跌到股票的实际价值以下，股民就会买进，股价随着大家的买进停止下跌。实际上，空头只有在股价过高的时候卖出股票才能赚大钱。可以肯定的是，内线人士绝不会向世界宣布任何事实。

华尔街专家的意见及看法，绝不能带给散户任何优势，你的投资利器就在你自己身上，投资你了解的产业和企业，才能发挥自身的优势。

买股票和养孩子差不多，别生太多让自己手忙脚乱，持股最好不要超过五只。

不要持太多只股票，最高的利润来自少量的股票的组合，这些股票你能充分了解。

这个游戏的本质就是这样，所以，股民们应该认识到，知情人是少数人，而且他们绝对不会透露真相。

大家应当时刻谨记股票交易的基本原则。股价上涨时，不要问它为什么涨，持续买进自然会推动股价上涨。只要股价持续上涨——上涨中偶尔会出现合理的小幅回落——继续跟进就是稳妥的操作。但如果经过长时间的持续上涨后，股价突然回档，逐渐开始下跌，其间虽偶尔小幅反弹，你就明白，很显然，最小阻力方向已经从上涨变为下跌了。情况就是这么简单，为什么要苦苦寻求解释呢？

我的经验足以证明，在投机买卖中真正赚得的利润，都来自那些一开始就保持盈利的头寸。 投机者必须对最初的小额亏损进行及时止损，以免给自己带来更大的损失。只有这样，才能将资金账户维持在很好的状态，最大程度地保存自己的资金实力。

当一只股票的价格开始下跌时，没人能够预测到它的底部在哪。同样，在一轮显著的上涨行情中，也没人能够预测到它的顶部在哪。绝对不要因为某只股票看起来价格太高就卖掉它。反过来，绝对不要因为某只股票从前一个最高点大幅下跌就买进它。

在等到股市变化本身验证你的判断之前，千万不要轻率地认定自己的判断就是正确的，只有在通过股市本身的验证之后，才能对自己的判断盖棺定论，因为股市的市场效应未必如你所预期的那样明确。你的预期反应的是"是怎样"，而市场效应反应的则是"应该怎样"。下面

对投资者或投机者来说，除非你的个人观点能左右市场的变化，否则你的个人观点将变得一文不值。

举个例子，某只股票当前的成交价为25美元，此前它已经在22美元到28美元的这个区间徘徊了很长一段时间。假如你预测这只股票最后将上涨到50美元，也就说现在这只股票的成交价格是25美元，而你预测它能上涨到50美元。别激动！一定要耐心等待！等这只股票表现出活跃的态势，等它越过28美元这个关键点，创下历史新高，比如上涨到30美元。这时，你才能从这只股票的真正走势中证实你的判断是正确的。这只股票已经进入了极其强势的状态，不然根本达不到30美元的交易价格。只有观察到这只股票出现了这些变化后，你才能判断，这只股票很可能处在大幅上涨过程中——大趋势已经开始启动了。到了这个时候，你就可以为自己的判断盖棺定论了。如果你没有在25美元的时候买进，也千万不要懊恼。也许，如果你真的在那个价位买进的话，结果很可能没有你想象的那么乐观。我们可以设想一下：如果你在25美元买进，此后股票价格在22美元到28美元的区间内徘徊了很长一段时间，在此期间，你耐心地等啊等啊，直到被折磨得疲惫不堪，也没等到股票大幅上涨行情的到来。于是，在真正的上涨行情启动之前，你就已经痛苦地抛掉了原来的仓位。正因为你是在上涨行情没有真正到来之前以较低价格卖出的，所以你也许会懊恼自己过去不明智的行为，从而错失了后来本可以再次买进的机会。

总之，我认为：作为一个成功的投资者或投机者，他在入市做多或做空之前必定会有非常充分的理由，而且他们必定是根据自己独特的股市判断准则来确定首次入场建仓的时间。

在这里我必须再次强调，当股票行情真正启动时，一定会出现明确的交易时机。我坚信，任何具有投机者本能和耐心的人都一定会想方设法建立某种股市判断准则，借以正确预测入场建仓的最佳时机，成功的投机者绝对不会允许自己仅仅依靠单纯的猜测来进行市场操作。

请努力让自己熟悉一只股票，或者熟悉很多不同的股票板块。如果你能根据自己的行情记录准确推算时间要素，那么总有一天，你能准确判断出重大行情到来的时机。如果你可以针对行情记录进行正确解读，那么你就能在任何股票板块中挑选出它的领涨股。再重申一遍，你必须亲自维护行情记录，亲手记录数字，千万不能让任何人代替你做这些工作。在你身体力行的过程中，你会惊奇地发现你的脑海中会时时涌现出各种各样的新点子。最为可贵的是，这些点子是任何人都没法教给你的，因为它们是你自己观察和思考得来的，只有你自己知道，因此你应当保守这些秘密。

在本书中，我告诉了投资者和投机者一些"禁忌"。其中一条主要规则就是，绝对不能把投机和投资混为一谈。投资者之所以常常遭受巨大的亏损，没有别的原因，就是因为他们当初抱着投机的心态来进行股票交易，结果可想而知，他们因此付出了极大的代价。

另一个原则是：如果第一笔交易已经处于亏损状态，就绝不能为了摊低亏损而继续跟进。请把这个原则深深地铭记在心。

那些终日企图在市场小规模的波动中获利，甚至不愿意放过任何一次微小的赚钱机会的投机客，永远不可能在下一轮重大行情发生时占据一席之地。

每年仅有屈指可数的几次大机会，也许只有四五次，碰到这样的机会时你才能允许自己全身心投入股市。其他时间里，你应该耐心等待市场逐步形成的下一次大行情。

我要再次强调一点，对于每一个普通投资者或投机者而言，人性内在的弱点就是自己最大的敌人。也许，总有人会想不明白，一只股票在经历了一轮大幅度的上涨后开始下跌，为什么就不能再次上涨呢？当然，下跌之后它也许会再从某个价格水平上开始上涨。但是，你凭什么指望它在你希望它上涨的时候，它就恰好上涨呢？还有一种更大的可能是，它不会上涨了。退一步说，即使它如愿地上涨了，优柔寡断的投机者估计也可能把握不好这个机会。

必须彻底抛弃一切一厢情愿的想法；一个人不可能在所有的投机中始终保持成功；每年仅有屈指可数的几次大机会，也许只有四五次，碰到这样的机会时你才能允许自己全身心投入股市；其他时间里，你应该耐心等待市场逐步形成的下一次大行情。

一轮真正的行情绝不会在它启动的那天就马上结束，而是会运行一段时间才终结。我身处远离股市的山中，这有利于我保持耐心，为这些真正的大行情留下它们所需的充足时间。我会把在报纸上看到的股票价格记入我的行情记录中，一旦某天我观察到刚刚记录下来的价格与已经明确持续了一段时间的行情发展不一致时，我会立刻做出决定，下山亲自进行交易。"

众所周知，股市价格总是不断上下波动的，过去如此，将来也会一直如此。我一直认为，在那些股市的重大行情背后，必定存在着一股不可抗拒的力量。事实上，你也只需了解这一点就足够了。如果你对价格波动背后的一切原因都想深究，那么这种过于琐细和好奇的行为反而会弄巧成拙。你的思维可能会被这些旁枝末节的琐事遮蔽，你对股市行情的判断也会因此受到影响，这就是这种行为带给你的风险。

所有投机者几乎都有一个通病，那就是急于求成，企图在极短的时间内赚得钵满盆盈。他们根本就没打算花费两到三年的时间来让自己持有的资本增值500％，而是妄图在两三个月之内就达到这一目标。

还有一点，也许值得一提。投机者每当结束一笔成功交易之后，都应取出其中一半的利润储存起来。这一点必须当成一项规则来执行。因为只有投机者结束一笔成功交易后从账户里取出的那部分钱，才是唯一真正从华尔街赚到的钱。

太多的投机者总是任凭一时冲动买进或卖出股票，这导致他们几乎会在同一个价位上满仓买入。这种方式是极其错误而且危险的。

市场会简单明了地告诉我们什么时候在犯错误，因为犯错误时我们一定在赔钱。当我们第一次认识到自己正在犯错误时，就是当机立断清仓离场之时，我们应该勇于接受亏损的事实，努力保持微笑，并仔细研究行情记录，尽量找出导致错误的原因，然后耐心静候下一次大机会。

坦率地说，对于来自内心的莫名奇妙的不安和警告，我总是秉持怀疑态度，通常我更青睐于采用客观的科学准则。但是，实际情况却总是倾向于我突然萌发的感知力，而不是科学准则。有时，当所有事情似乎都一帆风顺时，内心却会突然涌起一种忐忑不安的感觉。恰恰是通过密切关注这种感觉，我才能在很多场合获益颇丰。

终日在股市中买进卖出，捕捉小规模的日内波动。这是不对的，幸亏我及时清醒地认识到这个错误。从此以后，我决定忽略所有股票价格的微小波动。

频繁的交易便是盲目的交易，是华尔街上甚至最专业的投机者都会亏损的主要原因，他们把股票交易当成了一份有固定收入的工作，总觉得自己每天都应该赚些钱回家。不过请理解我，当时我还只是个孩子，并不懂得后来学到的这些东西，并不知道15年后发生在自己身上的事能让我大彻大悟。

我当时很年轻，很多人都想占我的便宜，所以我面临很多障碍，但这也让我学会了自强。那些同行看我年轻，都认为我能赚到钱纯属瞎猫撞着死老鼠。可是他们不明白，如果瞎猫总能碰上死耗子，那也就不太一样了。

即使在短期投资中，抄底和逃顶的结果是值得羡慕的，但是不值得追随，因为这些人没有一个起初以抄底或逃顶为目的。以抄底和逃顶为目标，就像提着灯笼找影子一样。

"躁"，是一种通病，这和"快"是两个完全不同的概念。

我输得只剩下在哈丁公司的保证金了，但我并没有生气。很明显，我准确地解读了行情，却像个傻子似的让艾德·哈丁动摇了自己的决心。谴责别人是毫无意义的，它并不能改变什么，只会浪费时间。我

这只是众多事例中的一件。在华尔街，那些想从股市赚钱买汽车、手镯、摩托艇或油画的人，无一例外都亏了。股市是吝啬的，它拒绝替任何人支付任何生日礼物，它拒付的这些生日礼物都可以用来盖一座大医院了。想让市场成为乐善好施的仙女的动机，是在华尔街亏钱的原因之一，也是最常见最顽固的原因。
