#+title: 像艺术家一样思考-藏在名画里的创意思维 (Think Like An Artist)

想要拥有个性创意，就要用一颗童心来看世界。因为孩子的眼睛里总是充满好奇，他们对进入他们视野的事物都充满了新鲜感和好奇心。但随着年龄的增长，明亮的眼眸被“偏见”的尘土侵染，对好奇的热情和意志也就随之消失殆尽了。此时，在被尘土所占据的眼睛里，除了陈腐和倦怠，再也容不下其他任何东西。

好奇心会使你在所看到的画面的基础上，开阔视野，增强思考问题的长远性的能力。看到完全背离现实的画面，观赏者就会情不自禁地思考画家这样做的意图是什么。玛格利特之所以重复使用打破事物常规性的创作方式，就是为了软化人们僵化的思想。

我在1926—1936年间创作的作品，都是在探寻怎样通过改变事物的摆放位置来制造出特殊的效果。在那期间，我尝试把人们所熟悉的日常事物与它所处的环境剥离开来，从而给人们造成一种视觉冲击。比如说，把路易·菲利普风格的桌子置于广袤的冰原中；让家里的墙壁产生龟裂；让原本待在脸上的伤疤漂浮于空中；把桌子翻个底儿朝天，放在树林里，就犹如一座高耸入云的巨塔。也正因为使用了这种创作方法，原本平凡无奇的事物在我的画里就变成了另一种独特的存在。

为了在创作上更上一层楼，我又想出了另一种方法，那就是让熟悉的事物异化变形。例如，把树木的材质换成空气，让它们构筑起天空……把普通的事物异化为人们想象之外的东西，用这种方式可以否定人类意识和外部世界。

毛皮和茶具这两个在现实生活中毫不相干的物品搭配在一起，透出一种新鲜感和特别感。奥本海姆创作如此“糟糕”的作品只是为了成为超现实主义艺术的先锋。超现实主义艺术是以激发深藏在人内心的想法和情感为创作目的的一种美术运动。超现实主义艺术家认为人的本性并不像容貌一样展露在外面，通常情况下都被埋藏在自己的潜意识之中，如果能很好地释放人类的潜意识，我们的生活将会变得更加美好。

我决心要画我所看到、所感受到的花，并赋予它我的意义。 但，要把它放大。 那样人们就会大吃一惊，并割舍出宝贵的时间来欣赏这朵花。 即便你是一位忙碌的纽约人，也必然会抽出时间来看我的画。

时尚艺术家们之所以致力于创造与大众息息相关的美术作品，是具有绝对动机的。现代美术太深奥了，简直令人摸不着头绪，即便是美术专家也不得不下一番苦功，才能窥其端倪。因而，大众理所当然要选择离开令人头痛的现代美术，转投引发共鸣的大众文化旗下。如此一来，艺术家们深深体会到了危机感，他们发现，将纯美术与大众熟知的素材相融合是必要的。

画可以分为内容与形式两部分。所谓内容，就是画面所表现出来的主题或故事、信息；所谓形式，就是构成画的各种要素，如线条、色彩、形态等。一幅好画，必定是内容与形式完美融合的产物，画的内容决定着画的主题，多关注主题，有助于我们去理解和赏析作品。

它告诉我们，观察事物不能只看局部，而要着眼于全局。也就是说，不要让自己成为眼界狭隘的人，只看到树木却忽略了整个森林，或是只看到森林却忽略了树木。用显微镜看世界的人，纵然事事细腻，却只能看到眼前的那一块天地，看不到长远的未来。相反，用望远镜看世界的人，虽然视野开阔，却粗心大意。艺术家们意在告诫世人，在生活中要结合微观视野与宏观视野，去看待一切。他们之所以要创作神奇的双重画，其目的就是为了把自己的人生感悟，以一种轻松、愉悦的方式传达给世人。

两位学者一致认为，人类是穿插在两个世界中的矛盾体。一个世界为理性所支配，另一个则是由本能或直觉主宰的无意识世界。较之理性，“无意识”占据着更为广阔的领土，若“人的意识”是一座冰山，那么理性就只是冰山一角。但不幸的是，人类平时根本意识不到如此重要的无意识世界的存在。无意识即没有意识，是一个被隐藏的神秘世界。殊不知，人类意识不到的这个混乱、无秩序、无法无天的世界，就是创造力的源泉——直觉、第六感、灵感的产地。

事实上，大多数人都具有这样一种倾向，即贬斥身边之物的价值、无视周围的事物，渴望得到遥不可及的东西，忽略创意就在近处、就在生活中这一事实。其实我们并不知道，在熟悉的领域中寻找创意，目标往往更容易实现。然而，就是因为我们的无知，可贵的创意才会离我们越来越远。那么，现在就让我们换一个角度去审视世界，去寻找平凡、熟悉甚至遭人鄙夷的事物所存在的价值，这便是利用“缝隙战略”走向成功的诀窍。

我们自外部世界体会到的感动，可谓少之又少。事实上，真正的感动出自于艺术家的想象力。要想激发想象力，我们就必须闭上肉眼，用灵魂的眼睛去赏画。如此，我们的眼睛，较之眼前清晰的事物，会更执迷于那些缥缈、模糊的东西。

艺术作品与观赏者进行沟通的最佳方式，就是暗示，因为暗示可以牵引出观赏者内心的潜在情感与想法。

眼睛主导着天文学，同时，它也是引导人类艺术走向创造之巅的首要感官。若想将无比美丽的自然形象刻画得惟妙惟肖，眼睛便是必要的道具。

请画家们牢记：如果你无法成为临摹自然界一切形态的万能人，最终也不会成为一名优秀的画家。而如果你不对自然界的各种形态进行观察，并将其印在自己的脑海中，你也就无法成为万能人。作为画家，我们就是要分析构成“自然”的各类必要因素，并将结果用艺术语言表达出来，画家的职责就是做一个这样的翻译员。

所谓有创意的人，是指对现存领域做出改造，对现有思想、行为进行变革，或是能够创作新作品的人。

艺术绝不会凭空而降。人们的想法在不断发生着变化，反映人类思想的艺术也必然会随之进步。

近代美术正在走向衰退，形式主义美术威力不再……若想振兴艺术，就必须打破禁锢。消除障碍不是为了夺取自由，而是为了破坏。要彻底摧毁骨架、毁坏形体，驱散原有的意念，也就是说，要让事物处于起始状态。

成功非常重要。人们常说，作为一个艺术家，成功还在其次，最重要的是对艺术的热爱。但我认为，这种想法是错误的！艺术家必须成功，这不仅能够激发出生命的能量，同时也会赋予艺术家一个创作的动机。

所谓抽象画，是指无法区分形象的画；而构想画，则是指能够识别主题及内容的画。“抽象”出自“抽取”一词，其意为抽取隐藏于目标对象内部的本质及基本特征。抽象画之所以看上去难以理解，其原因在于，它所描绘的并不是现实世界或事物的外表，而是结合线条、形态、色彩等多种要素去表达作品的意义。

美术作品由内部要素与外部要素两部分构成。所谓内部要素，是指艺术家自灵魂深处释放出来的情感。这种情感会感染到观赏者的灵魂，使他们也产生类似的情绪……我将这种对世间万物潜在灵魂的审视，称为内部洞察。这种洞察力能够穿透外部形态的硬壳，深入到事物的本质中去。当人们触及事物的本质时，就会感觉到事物的脉搏在跳动。

抽象美术以其独特的形式向观赏者发出了挑战。它要求观赏者以全新的视角去欣赏美术作品。若要解析抽象美术，就要敢于舍弃以往的习惯，摒除“画中事物依何而画”的传统意识……抽象美术不仅能够使人们了解到肉眼看到的、具体的、静态的一面，同时，还会让人们感悟到肉眼看不到的、非物质的、动态的一面。

正确并不代表真实，重要的是，我们能否画出与众不同的作品。对于一个真正的画家而言，没有比画一朵玫瑰更为困难的事情了，因为若想画好玫瑰，就要忘记以往画过的所有玫瑰。

然而，马蒂斯建立的“色彩王国”，曾受到美术界的强烈质疑。因为当时的人们认为，美术中的首要要素是素描，即线条。画家们将素描比喻为理性的表现，而将色彩比喻为感性的表现。他们只重视素描，并不关注色彩。但马蒂斯认为，色彩才是美术中的首要要素，因此他不使用素描，而是通过色彩来描绘事物。他将树木涂成红色，人的皮肤涂成蓝色，而天空则涂成黄色。因为马蒂斯在作品中使用的色彩与目标对象本色大相径庭，且又非常浓重，因此人们又称他为“野兽派画家”。也就是说，他将野兽般的情绪，通过鲜艳的颜色反映到了自己的作品之中。

让人专注三十分钟以上，已经是件非常困难的事情。而我，吸引人们的眼球已整整二十年。秘诀只有一个——让人们只想到达利、只谈到达利。

我们喜欢他——一个凡人卢梭，因为命运中的种种坎坷根本打不倒他，他总是拥有那份天真、勇气以及纯洁。一个艺术家——卢梭，我们仍然喜欢他，因为他拥有惊人的感受力以及对于绘画的热情，这足以造就伟人，除毕加索、马蒂斯以外，同时代画家中，能够创作出如此独特作品的人，简直少之又少。

卢梭之所以会遭到美术家们的蔑视，是因为以画家身份参展的他却不具备任何描绘技巧，而且素描能力也确实令人不敢恭维。例如，他在画人物画时，为了检测模特耳鼻口目的间距及身体尺寸，竟使用尺子对人体进行测量；为了找到与肤色相吻合的色彩，他竟然直接拿颜料与模特的肤色进行比较。美术家们毫不客气地公开取笑、辱骂卢梭。当时，有一位名叫阿波里奈尔的诗人，对这位被美术界孤立的卢梭表示了深深的同情，他说：“没有一个艺术家像卢梭那样，遭受过别人那么多的耻笑。然而，也没有一个艺术家像卢梭那样，坦然接受了来自各方的耻笑。他的灵魂就是那么的单纯。”

在发病期间，我无法认清任何事物。但是这可怕的痛苦会让我更加热衷于画画。就像生命受到威胁的矿工会更加急于挖出矿石逃离矿洞一样……身体的极度痛苦越是让我感觉粉身碎骨，我离艺术家、创作家也就越近。

病魔、疯狂和死亡是围绕着我的摇篮飞来飞去的天使并且会伴随我一生……我的一生是在深不见底的悬崖边缘行走，从一块石头跳到另一块石头……受到这种深刻的焦虑感的折磨，我一直设法用我的艺术来表现这种感觉。没有焦虑和疾病的折磨，我就像是一艘没有舵的船。

我平生的夙愿就是和大自然和谐地融为一体。 我生存的意义就是用画笔诠释大自然的造化和法则。 除此之外我没有其他的追求。 大自然是永恒的存在，她有无穷的力量。 和大自然相比，人类是如此的微不足道。

人的一生中，最重要的事情就是认识自己。我们对于自己，其实是很无知的，我们常常不知道自己喜欢什么、讨厌什么、追求什么，也不知道自己爱什么人、恨什么人，甚至连自己的性格趋向都不是很清楚。 即使我们有时可以很敏锐地洞察出别人的心理或优缺点，可以很容易了解他人的气质和性格，但对于自己却很难做到真正的认识。为什么最难认识的是自己呢？因为我们就是那个最熟悉自己的陌生人，离我们最近的东西，往往最难被认知。

