#+title: Cover Letter

@2015

My name is Yan Zhang. I'm from China. I'm a software engineer with years experience of distributed systems and system software development on Linux. I have built several large-scale(thousands nodes) distributed systems and worked on the infrastructure in Baidu which is the biggest search engine company in China. Then I joined a startup "Umeng" which focus mobile device and worked on data processing and analysis by leveraging Hadoop/Spark, HBase and Storm. Meanwhile I have worked two remote jobs and made myself accustomed to work remotely and work with global developers. In the first remote job, all team players work at Helsinki except me. The second remote job consists of developers from US, UK and Poland.

Besides experience of distributed systems design and implementation:
- proficient in C/C++ and familiar with Java and Python and Scala.
- solid knowledge of data structures and algorithms.
- good at performance tuning and optimization of systems based on strong knowledge of CPU, Memory and IO.
- comfortable with concepts of function programming. Read the SICP and Little Schemer at college just for fun.
- good understanding about compiler technique. Designed a language from scratch and implemented its compiler to generate x86 assembly code.
- learned machine learning theory and practical technique on Coursera in the past 6 months, and took part in few competitions on kaggle.

Blog: http://dirtysalt.github.io
Github: https://github.com/dirtysalt/
LinkedIn: https://www.linkedin.com/in/dirtysalt

Best Regards
Yan
