#+title: mac
相对ubuntu来说，mac还是非常容易上手的。我相信同学的说法:"你拿到的是世界上最好的笔记本"。大部分时候我主要用它阅读文档和浏览网页，只是偶尔在上面写写代码（开发还是觉得在Linux/Ubuntu上好点）

** 软件列表
mac软件还是非常齐全的，我大致安装了下面这些东西。感觉brew可用软件并不是太多，常用软件都可以通过dmg找到。

-----
下面软件是通过手动下载dmg安装的:
   - Evernote
   - brew # apt-get for Mac.
   - QQ
   - 字典 # mac自带词典已经非常好用，并且附带了许多词库。在字典的偏好设置里面可以选择这些词库。可选的还有金山词霸，有道词典
   - Tunnelblick # openvpn似乎在mac下面似乎有bug.
   - VirtualBox
   - Chrome
   - IntelliJ
   - AirServer # AirPlay Server.
   - 网盘 # 可选的有百度云盘，金山快盘（可以在Ubuntu上运行）
   - 音乐 # 可选的有百度音乐，网易云音乐
   - Skype
   - Alfred
   - iTerm2
   - iWork # 比M$ Office效果好多了

-----
下面软件是通过brew自动安装的:
   - # brew install openvpn # 翻墙代理
   - brew install emacs --cocoa --srgb
     - #note@2013-10-30: 中途有段时间我想重装，但是在安装patch的时候需要访问raw.github.com被墙
     - http://emacsformacosx.com/ 从这里可以直接安装发行版本
   - # brew install svn --unicode-path
   - # brew install ispell
   - # brew install aspell
   - # brew install tmux
   - # brew install cscope
   - brew install ctags

brew的常用选项有下面这些：
   - brew search <package> # 搜索package
   - brew install <package> # 安装package
   - brew options <package> # 查看package安装选项

** 如何截屏
使用Command+Shift+4可以进行截屏，ESC可以退出，截图会保存在桌面上。

或者使用Command+Shift+Control+4进行截屏，完成后图片保存在剪切板上。

** 设置触控板
系统偏好设置 => 触控板 => 设置"轻拍来点按". 不然每次左键都要用力按下.

** 控制休眠
  - 系统偏好设置=》节能器
  - 电池模式下面使用默认配置
  - 电源适配器下面使用默认配置，然后修改”电脑进入睡眠“为”永不“

** VirtualBox启动问题
启动遇到如下错误"VM (VERR_SUPLIB_WORLD_WRITABLE) with following details: code d'erreur: NS_ERROR_FAILURE (0x80004005) composant: console interface: IConsole {515e8e8d-f932-4d8e-9f32-79a52aead882}". 查看日志之后发现/Applications权限存在问题，修改权限到755之后正常启动。

** 启动sshd服务
系统偏好设置 -> 共享 -> 远程登陆

** 禁止iPhoto人脸检测功能
http://sullysrants.com/2014/02/disable-stoppause-iphoto-faces-detection/

defaults write com.apple.iPhoto PKFaceDetectionEnabled 0
