#+title: 智能时代

在数据收集过程中，非常忌讳那种“大胆假设，小心求证”的思维方式，因为在很多时候，如果事先有了定论，再找数据来证实它，总能找到有力的证据，而这些看似被数据证实的结论，很可能与真实情况相差十万八千里。因为在数据是收集时，我们需要强调它是在无意之间完成的。

在大数据这个概念不断地被炒作，数据变得越来越值钱时，一些公司和个人开始赤裸裸地收集用户数据，然后想办法卖掉。事实上这样刻意收集来的数据意义不大，因为收集数据的过程会引起用户的警觉，恐慌和方案，一部分对信息敏感的人可能会关闭收集数据的传感设备，导致收集的数据不全面（ _这个应该还是占少数吧，不会对数据完备性有太大影响_ )；而另一部分人的行为会变得不自然。这种变了形的数据，既不具有统计意义，也失去了大数据的完备性。因为，真正高明的公司都会像微软，Apple和Google那样采用曲线救国的办法。有些时候，为了收集数据，这个弯妖娆的特别大。

虽然各国政府都试图通过各种手段帮助那些从业人员掌握新的技能，但是收效甚微，因为上一代人很难适应下一代的技术发展。事实上，消化这些劳动力主要靠的是等待他们逐渐退出劳务市场，而并非他们真正有了新的出路，能够和以前一样称心如意地工作。这就是每次技术革命都需要花半个世纪来消除它带来的动荡的原因。唯一不同的是，在一百年前，各国政府认识不到关心这些被产业淘汰的的从业人员的重要性，因为让社会很动荡。（ _朱镕基时代精简一大批国企员工，看上虽然很激进，社会影响也很大，但是也加快了市场经济在中国的发展，不然也到等待这批人退休市场经济才能逐渐在中国站稳脚跟，恐怕那个时候中国会错过信息技术革命这波浪潮_ ) 如今，各国意识到社会稳定很重要，因此即使很多人并不创造价值，也只好“养着”。为此，有些国家将无所事事的人强制塞到公司里（比如日本和欧盟），有些国家不肯淘汰过剩产能（比如中国），但解决问题的途径都是一个“耗”字。耗上两代，社会问题就解决了。（ _人类科技速度是不断加快的，信息革命还没过去半个世纪，智能革命又来了。恐怕两代的时间，又有新的一波浪潮要来_ )

那些曾经为人类的文明做过贡献，但是已经被技术革命所淘汰的员工，唯一的希望就是他们的后代能够进入一个新的行业。这实际上就是靠时间慢慢地消化技术革命带来的负面影响。

今天的世界和200年前已经完全不同了，消化掉技术革命的影响要比工业革命时难得多。由于全球化，全世界已经没有空白的市场可以开拓了。英国人在19世纪中期能够多上相对富裕而从容的生活，是因为他们只需要解决几百万产业工人的生活和工作问题就可以。( _这也就解释了为什么英国需要在世界各地开拓新殖民地，这让我想起了罗辑思维一期《弱者的思维》里面提到过这点_) 整个19世纪，是用全球的市场，解决当时只占世界人口很小一部分的产业工人的生活问题，相对要比今天容易得多。

在智能革命全面到来的时候，不可能像过去那样，把农业人口变为城市人口，把第一第二产业变为第三产业那么简单。踏上智能革命的浪潮，成为那2%的可以制造智能机器的人，或者将智能应用起来的人，才能让自己这个时代中生存和受益。
